<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        * { font-family: DejaVu Sans, sans-serif; }
        body { color: #1f2937; font-size: 12px; margin: 0; }
        .wrap { padding: 32px 36px; }
        .header { border-bottom: 3px solid #2563eb; padding-bottom: 14px; margin-bottom: 20px; }
        .brand { font-size: 22px; font-weight: bold; color: #2563eb; }
        .brand small { color: #6b7280; font-weight: normal; font-size: 11px; }
        .rx { float: right; font-size: 40px; color: #2563eb; font-weight: bold; line-height: 1; }
        .meta { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        .meta td { padding: 4px 0; vertical-align: top; }
        .meta .label { color: #6b7280; width: 90px; }
        .meta .value { font-weight: bold; }
        .section-title { font-size: 13px; font-weight: bold; margin: 18px 0 8px; color: #111827; }
        .box { background: #f8fafc; border: 1px solid #e5e7eb; border-radius: 6px; padding: 10px 14px; margin-bottom: 6px; }
        table.meds { width: 100%; border-collapse: collapse; margin-top: 6px; }
        table.meds th { background: #eff6ff; text-align: left; padding: 8px 10px; font-size: 11px; color: #1e3a8a; border: 1px solid #dbeafe; }
        table.meds td { padding: 8px 10px; border: 1px solid #e5e7eb; vertical-align: top; }
        .status { display: inline-block; padding: 2px 10px; border-radius: 999px; background: #dcfce7; color: #166534; font-size: 11px; font-weight: bold; }
        .footer { margin-top: 40px; border-top: 1px solid #e5e7eb; padding-top: 12px; color: #9ca3af; font-size: 10px; }
        .sign { margin-top: 48px; text-align: right; }
        .sign .line { display: inline-block; border-top: 1px solid #6b7280; padding-top: 4px; min-width: 200px; text-align: center; color: #374151; }
    </style>
</head>
<body>
    <div class="wrap">
        <div class="header">
            <span class="rx">&#8478;</span>
            <div class="brand">DocSlot <small>&mdash; Medical Prescription</small></div>
        </div>

        <table class="meta">
            <tr>
                <td class="label">Patient</td>
                <td class="value">{{ $prescription->patient->user->name }}</td>
                <td class="label">Date</td>
                <td class="value">{{ $prescription->created_at->format('M j, Y') }}</td>
            </tr>
            <tr>
                <td class="label">Doctor</td>
                <td class="value">Dr. {{ $prescription->doctor->user->name }}</td>
                <td class="label">Status</td>
                <td><span class="status">{{ ucfirst($prescription->status) }}</span></td>
            </tr>
        </table>

        <div class="section-title">Diagnosis</div>
        <div class="box">{{ $prescription->diagnosis ?: 'Not specified.' }}</div>

        @if ($prescription->notes)
            <div class="section-title">Notes</div>
            <div class="box">{{ $prescription->notes }}</div>
        @endif

        <div class="section-title">Medications</div>
        <table class="meds">
            <thead>
                <tr>
                    <th>Medication</th>
                    <th>Dosage</th>
                    <th>Frequency</th>
                    <th>Duration</th>
                    <th>Instructions</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($prescription->medications as $med)
                    <tr>
                        <td>{{ $med->medication_name }}</td>
                        <td>{{ $med->dosage }}</td>
                        <td>{{ $med->frequency }}</td>
                        <td>{{ $med->duration ?: '—' }}</td>
                        <td>{{ $med->instructions ?: '—' }}</td>
                    </tr>
                @empty
                    <tr><td colspan="5" style="text-align:center; color:#9ca3af;">No medications listed.</td></tr>
                @endforelse
            </tbody>
        </table>

        <div class="sign">
            <div class="line">Dr. {{ $prescription->doctor->user->name }}</div>
        </div>

        <div class="footer">
            This prescription was generated by DocSlot on {{ now()->format('M j, Y g:i A') }}.
            It is valid only with the prescribing doctor's authorization.
        </div>
    </div>
</body>
</html>
