// Regenerates a Bootstrap Icons font+CSS subset containing only the bi-* classes
// actually referenced in frontend/src. Re-run this (`node scripts/subset-icons.mjs`)
// whenever an icon is added to or removed from the app.
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import subsetFont from "subset-font";

const root = path.dirname(fileURLToPath(import.meta.url));
const frontendRoot = path.join(root, "..");
const srcDir = path.join(frontendRoot, "src");
const biPkg = path.join(frontendRoot, "node_modules", "bootstrap-icons");

async function walk(dir) {
  const { readdir } = await import("node:fs/promises");
  const entries = await readdir(dir, { withFileTypes: true });
  let files = [];
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) files = files.concat(await walk(full));
    else if (entry.isFile() && /\.(js|html)$/.test(entry.name)) files.push(full);
  }
  return files;
}

const files = await walk(srcDir);
const iconNames = new Set();
const re = /\bbi-[a-z0-9]+(?:-[a-z0-9]+)*\b/g;
for (const file of files) {
  const text = await readFile(file, "utf8");
  for (const match of text.matchAll(re)) iconNames.add(match[0].slice(3));
}

const codepoints = JSON.parse(await readFile(path.join(biPkg, "font", "bootstrap-icons.json"), "utf8"));
const used = [...iconNames].filter((name) => codepoints[name] !== undefined).sort();
const missing = [...iconNames].filter((name) => codepoints[name] === undefined);
if (missing.length) {
  throw new Error(`Icon name(s) not found in bootstrap-icons.json: ${missing.join(", ")}`);
}

const chars = used.map((name) => String.fromCodePoint(codepoints[name]));
const fontBuffer = await readFile(path.join(biPkg, "font", "fonts", "bootstrap-icons.woff2"));
const subsetBuffer = await subsetFont(fontBuffer, chars.join(""), { targetFormat: "woff2" });

const assetsDir = path.join(srcDir, "assets");
await writeFile(path.join(assetsDir, "bootstrap-icons-subset.woff2"), subsetBuffer);

const rules = used
  .map((name) => {
    const hex = codepoints[name].toString(16);
    return `.bi-${name}::before { content: "\\${hex}"; }`;
  })
  .join("\n");

const css = `/*!
 * Bootstrap Icons subset — generated by frontend/scripts/subset-icons.mjs
 * Contains only the ${used.length} icon(s) actually used in frontend/src.
 * Source: Bootstrap Icons v1.13.1 (https://icons.getbootstrap.com/) — MIT License
 */

@font-face {
  font-display: block;
  font-family: "bootstrap-icons";
  src: url("./assets/bootstrap-icons-subset.woff2") format("woff2");
}

.bi::before,
[class^="bi-"]::before,
[class*=" bi-"]::before {
  display: inline-block;
  font-family: bootstrap-icons !important;
  font-style: normal;
  font-weight: normal !important;
  font-variant: normal;
  text-transform: none;
  line-height: 1;
  vertical-align: -.125em;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

${rules}
`;

await writeFile(path.join(srcDir, "bootstrap-icons.css"), css);

console.log(`Subset ${used.length} icon(s) into bootstrap-icons-subset.woff2 + bootstrap-icons.css`);
console.log(used.join(", "));
